Release 3.0.0
infinum/eightshift-forms-utils pull request #11
Opened 2024-07-20 11:11 UTC by iruzevic

# Description

TBA

# Screenshots / Videos

# Linked documentation PR

2024-07-20 14:15 UTC, piqusy approved these changes, later dismissed
Nice work 👏🏼 

Just one suggestions

2024-07-20 14:15 UTC, piqusy commented on src/Rest/Routes/AbstractUtilsBaseRoute.php
> +		// Populare action.
```suggestion
		// Populate action.
```
Please also apply to other instances

2024-07-22 06:35 UTC, dingo-d requested changes
Just minor grammar things I've noticed, nothing major 👍🏼

2024-07-22 06:35 UTC, dingo-d commented on src/Config/UtilsConfig.php
> +	// Never use this param as it is only of fallback purposes.
```suggestion
	// Never use this parameter because it is only used for fallback purposes.
```

2024-07-22 06:35 UTC, dingo-d commented on src/Rest/Routes/AbstractUtilsBaseRoute.php
> +		// These are required keys for each field.
```suggestion
		// These are the required keys for each field.
```

2024-07-22 06:35 UTC, dingo-d commented on src/Rest/Routes/AbstractUtilsBaseRoute.php
> +			// Check if all required keys are present and baiout if not.
```suggestion
			// Check if all required keys are present and bail out if not.
```

2024-07-22 06:35 UTC, dingo-d commented on src/Rest/Routes/AbstractUtilsBaseRoute.php
> +		// Bailout if we have any broken param.
```suggestion
		// Bail out if we have a broken param.
```

2024-07-22 06:44 UTC, dadadavorin submitted a review, later dismissed
👌

2024-07-22 10:56 UTC, dingo-d approved these changes

2024-07-22 11:05 UTC, piqusy approved these changes

2024-07-22 11:13 UTC, dadadavorin approved these changes

2024-07-23 05:53 UTC, merged